### ISSUE TITLE
Support for specifying VM's core and memory.

### ISSUE THREAD

**Issue by huasiy** [pixelsdb/vHive#3]
Currently, vhive will create VMs with fixed configurations, which makes it impossible for us to specify VM configurations for different functions. To address this issue, we can introduce two key value pairs in the knative service configuration file, which define the number of vCPUs and memory size of the VM.
```yaml
env:
  - name: VCPU_COUNT
    value: 1
  - name: MEMORY_MEGABYTE
    value: 200
```
Then extract values from `environmentVariables` in function `StartVMWithEnvironment` and pass to `getVMConfig`.
